// Helper function to get country flag URL by ISO code
export function getCountryFlagUrlByIso(iso: string): string {
  return iso ? `https://flagcdn.com/${iso}.svg` : "";
}

// Shared country codes for both contact form and product inquiry
export const COUNTRY_CODES = [
  // { code: "+971", flag: "🇦🇪", label: "UAE" },
  // { code: "+1", flag: "🇺🇸", label: "USA" },
  // { code: "+44", flag: "🇬🇧", label: "UK" },
  // { code: "+91", flag: "🇮🇳", label: "India" },
  // { code: "+86", flag: "🇨🇳", label: "China" },
  // { code: "+81", flag: "🇯🇵", label: "Japan" },
  // { code: "+61", flag: "🇦🇺", label: "Australia" },
  // { code: "+33", flag: "🇫🇷", label: "France" },
  // { code: "+49", flag: "🇩🇪", label: "Germany" },
  // { code: "+39", flag: "🇮🇹", label: "Italy" },
  // { code: "+36", flag: "🇭🇺", label: "Hungary" },
  // { code: "+43", flag: "🇦🇹", label: "Austria" },
  // { code: "+32", flag: "🇧🇪", label: "Belgium" },
  // { code: "+41", flag: "🇨🇭", label: "Switzerland" },
  // { code: "+34", flag: "🇪🇸", label: "Spain" },
  { name: "Afghanistan", code: "+93", iso: "af", flag: "🇦🇫" },
  { name: "Albania", code: "+355", iso: "al", flag: "🇦🇱" },
  { name: "Algeria", code: "+213", iso: "dz", flag: "🇩🇿" },
  { name: "Andorra", code: "+376", iso: "ad", flag: "🇦🇩" },
  { name: "Angola", code: "+244", iso: "ao", flag: "🇦🇴" },
  { name: "Antigua and Barbuda", code: "+1268", iso: "ag", flag: "🇦🇬" },
  { name: "Argentina", code: "+54", iso: "ar", flag: "🇦🇷" },
  { name: "Armenia", code: "+374", iso: "am", flag: "🇦🇲" },
  { name: "Australia", code: "+61", iso: "au", flag: "🇦🇺" },
  { name: "Austria", code: "+43", iso: "at", flag: "🇦🇹" },
  { name: "Azerbaijan", code: "+994", iso: "az", flag: "🇦🇿" },
  { name: "Bahamas", code: "+1242", iso: "bs", flag: "🇧🇸" },
  { name: "Bahrain", code: "+973", iso: "bh", flag: "🇧🇭" },
  { name: "Bangladesh", code: "+880", iso: "bd", flag: "🇧🇩" },
  { name: "Barbados", code: "+1246", iso: "bb", flag: "🇧🇧" },
  { name: "Belarus", code: "+375", iso: "by", flag: "🇧🇾" },
  { name: "Belgium", code: "+32", iso: "be", flag: "🇧🇪" },
  { name: "Belize", code: "+501", iso: "bz", flag: "🇧🇿" },
  { name: "Benin", code: "+229", iso: "bj", flag: "🇧🇯" },
  { name: "Bhutan", code: "+975", iso: "bt", flag: "🇧🇹" },
  { name: "Bolivia", code: "+591", iso: "bo", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", code: "+387", iso: "ba", flag: "🇧🇦" },
  { name: "Botswana", code: "+267", iso: "bw", flag: "🇧🇼" },
  { name: "Brazil", code: "+55", iso: "br", flag: "🇧🇷" },
  { name: "Brunei", code: "+673", iso: "bn", flag: "🇧🇳" },
  { name: "Bulgaria", code: "+359", iso: "bg", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "+226", iso: "bf", flag: "🇧🇫" },
  { name: "Burundi", code: "+257", iso: "bi", flag: "🇧🇮" },
  { name: "Cambodia", code: "+855", iso: "kh", flag: "🇰🇭" },
  { name: "Cameroon", code: "+237", iso: "cm", flag: "🇨🇲" },
  { name: "Canada", code: "+1", iso: "ca", flag: "🇨🇦" },
  { name: "Cape Verde", code: "+238", iso: "cv", flag: "🇨🇻" },
  { name: "Central African Republic", code: "+236", iso: "cf", flag: "🇨🇫" },
  { name: "Chad", code: "+235", iso: "td", flag: "🇹🇩" },
  { name: "Chile", code: "+56", iso: "cl", flag: "🇨🇱" },
  { name: "China", code: "+86", iso: "cn", flag: "🇨🇳" },
  { name: "Colombia", code: "+57", iso: "co", flag: "🇨🇴" },
  { name: "Comoros", code: "+269", iso: "km", flag: "🇰🇲" },
  { name: "Congo", code: "+242", iso: "cg", flag: "🇨🇬" },
  { name: "Costa Rica", code: "+506", iso: "cr", flag: "🇨🇷" },
  { name: "Croatia", code: "+385", iso: "hr", flag: "🇭🇷" },
  { name: "Cuba", code: "+53", iso: "cu", flag: "🇨🇺" },
  { name: "Cyprus", code: "+357", iso: "cy", flag: "🇨🇾" },
  { name: "Czech Republic", code: "+420", iso: "cz", flag: "🇨🇿" },
  { name: "Denmark", code: "+45", iso: "dk", flag: "🇩🇰" },
  { name: "Djibouti", code: "+253", iso: "dj", flag: "🇩🇯" },
  { name: "Dominica", code: "+1767", iso: "dm", flag: "🇩🇲" },
  { name: "Dominican Republic", code: "+1", iso: "do", flag: "🇩🇴" },
  { name: "East Timor", code: "+670", iso: "tl", flag: "🇹🇱" },
  { name: "Ecuador", code: "+593", iso: "ec", flag: "🇪🇨" },
  { name: "Egypt", code: "+20", iso: "eg", flag: "🇪🇬" },
  { name: "El Salvador", code: "+503", iso: "sv", flag: "🇸🇻" },
  { name: "Equatorial Guinea", code: "+240", iso: "gq", flag: "🇬🇶" },
  { name: "Eritrea", code: "+291", iso: "er", flag: "🇪🇷" },
  { name: "Estonia", code: "+372", iso: "ee", flag: "🇪🇪" },
  { name: "Ethiopia", code: "+251", iso: "et", flag: "🇪🇹" },
  { name: "Fiji", code: "+679", iso: "fj", flag: "🇫🇯" },
  { name: "Finland", code: "+358", iso: "fi", flag: "🇫🇮" },
  { name: "France", code: "+33", iso: "fr", flag: "🇫🇷" },
  { name: "Gabon", code: "+241", iso: "ga", flag: "🇬🇦" },
  { name: "Gambia", code: "+220", iso: "gm", flag: "🇬🇲" },
  { name: "Georgia", code: "+995", iso: "ge", flag: "🇬🇪" },
  { name: "Germany", code: "+49", iso: "de", flag: "🇩🇪" },
  { name: "Ghana", code: "+233", iso: "gh", flag: "🇬🇭" },
  { name: "Gibraltar", code: "+350", iso: "gi", flag: "🇬🇮" },
  { name: "Greece", code: "+30", iso: "gr", flag: "🇬🇷" },
  { name: "Grenada", code: "+1473", iso: "gd", flag: "🇬🇩" },
  { name: "Guatemala", code: "+502", iso: "gt", flag: "🇬🇹" },
  { name: "Guinea", code: "+224", iso: "gn", flag: "🇬🇳" },
  { name: "Guinea-Bissau", code: "+245", iso: "gw", flag: "🇬🇼" },
  { name: "Guyana", code: "+592", iso: "gy", flag: "🇬🇾" },
  { name: "Haiti", code: "+509", iso: "ht", flag: "🇭🇹" },
  { name: "Honduras", code: "+504", iso: "hn", flag: "🇭🇳" },
  { name: "Hong Kong", code: "+852", iso: "hk", flag: "🇭🇰" },
  { name: "Hungary", code: "+36", iso: "hu", flag: "🇭🇺" },
  { name: "Iceland", code: "+354", iso: "is", flag: "🇮🇸" },
  { name: "India", code: "+91", iso: "in", flag: "🇮🇳" },
  { name: "Indonesia", code: "+62", iso: "id", flag: "🇮🇩" },
  { name: "Iran", code: "+98", iso: "ir", flag: "🇮🇷" },
  { name: "Iraq", code: "+964", iso: "iq", flag: "🇮🇶" },
  { name: "Ireland", code: "+353", iso: "ie", flag: "🇮🇪" },
  { name: "Israel", code: "+972", iso: "il", flag: "🇮🇱" },
  { name: "Italy", code: "+39", iso: "it", flag: "🇮🇹" },
  { name: "Ivory Coast", code: "+225", iso: "ci", flag: "🇨🇮" },
  { name: "Jamaica", code: "+1876", iso: "jm", flag: "🇯🇲" },
  { name: "Japan", code: "+81", iso: "jp", flag: "🇯🇵" },
  { name: "Jordan", code: "+962", iso: "jo", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "+7", iso: "kz", flag: "🇰🇿" },
  { name: "Kenya", code: "+254", iso: "ke", flag: "🇰🇪" },
  { name: "Kiribati", code: "+686", iso: "ki", flag: "🇰🇮" },
  { name: "Kuwait", code: "+965", iso: "kw", flag: "🇰🇼" },
  { name: "Kyrgyzstan", code: "+996", iso: "kg", flag: "🇰🇬" },
  { name: "Laos", code: "+856", iso: "la", flag: "🇱🇦" },
  { name: "Latvia", code: "+371", iso: "lv", flag: "🇱🇻" },
  { name: "Lebanon", code: "+961", iso: "lb", flag: "🇱🇧" },
  { name: "Lesotho", code: "+266", iso: "ls", flag: "🇱🇸" },
  { name: "Liberia", code: "+231", iso: "lr", flag: "🇱🇷" },
  { name: "Libya", code: "+218", iso: "ly", flag: "🇱🇾" },
  { name: "Liechtenstein", code: "+423", iso: "li", flag: "🇱🇮" },
  { name: "Lithuania", code: "+370", iso: "lt", flag: "🇱🇹" },
  { name: "Luxembourg", code: "+352", iso: "lu", flag: "🇱🇺" },
  { name: "Macau", code: "+853", iso: "mo", flag: "🇲🇴" },
  { name: "Macedonia", code: "+389", iso: "mk", flag: "🇲🇰" },
  { name: "Madagascar", code: "+261", iso: "mg", flag: "🇲🇬" },
  { name: "Malawi", code: "+265", iso: "mw", flag: "🇲🇼" },
  { name: "Malaysia", code: "+60", iso: "my", flag: "🇲🇾" },
  { name: "Maldives", code: "+960", iso: "mv", flag: "🇲🇻" },
  { name: "Mali", code: "+223", iso: "ml", flag: "🇲🇱" },
  { name: "Malta", code: "+356", iso: "mt", flag: "🇲🇹" },
  { name: "Marshall Islands", code: "+692", iso: "mh", flag: "🇲🇭" },
  { name: "Mauritania", code: "+222", iso: "mr", flag: "🇲🇷" },
  { name: "Mauritius", code: "+230", iso: "mu", flag: "🇲🇺" },
  { name: "Mexico", code: "+52", iso: "mx", flag: "🇲🇽" },
  { name: "Micronesia", code: "+691", iso: "fm", flag: "🇫🇲" },
  { name: "Moldova", code: "+373", iso: "md", flag: "🇲🇩" },
  { name: "Monaco", code: "+377", iso: "mc", flag: "🇲🇨" },
  { name: "Mongolia", code: "+976", iso: "mn", flag: "🇲🇳" },
  { name: "Montenegro", code: "+382", iso: "me", flag: "🇲🇪" },
  { name: "Morocco", code: "+212", iso: "ma", flag: "🇲🇦" },
  { name: "Mozambique", code: "+258", iso: "mz", flag: "🇲🇿" },
  { name: "Myanmar", code: "+95", iso: "mm", flag: "🇲🇲" },
  { name: "Namibia", code: "+264", iso: "na", flag: "🇳🇦" },
  { name: "Nauru", code: "+674", iso: "nr", flag: "🇳🇷" },
  { name: "Nepal", code: "+977", iso: "np", flag: "🇳🇵" },
  { name: "Netherlands", code: "+31", iso: "nl", flag: "🇳🇱" },
  { name: "New Zealand", code: "+64", iso: "nz", flag: "🇳🇿" },
  { name: "Nicaragua", code: "+505", iso: "ni", flag: "🇳🇮" },
  { name: "Niger", code: "+227", iso: "ne", flag: "🇳🇪" },
  { name: "Nigeria", code: "+234", iso: "ng", flag: "🇳🇬" },
  { name: "North Korea", code: "+850", iso: "kp", flag: "🇰🇵" },
  { name: "Norway", code: "+47", iso: "no", flag: "🇳🇴" },
  { name: "Oman", code: "+968", iso: "om", flag: "🇴🇲" },
  { name: "Pakistan", code: "+92", iso: "pk", flag: "🇵🇰" },
  { name: "Palau", code: "+680", iso: "pw", flag: "🇵🇼" },
  { name: "Palestine", code: "+970", iso: "ps", flag: "🇵🇸" },
  { name: "Panama", code: "+507", iso: "pa", flag: "🇵🇦" },
  { name: "Papua New Guinea", code: "+675", iso: "pg", flag: "🇵🇬" },
  { name: "Paraguay", code: "+595", iso: "py", flag: "🇵🇾" },
  { name: "Peru", code: "+51", iso: "pe", flag: "🇵🇪" },
  { name: "Philippines", code: "+63", iso: "ph", flag: "🇵🇭" },
  { name: "Poland", code: "+48", iso: "pl", flag: "🇵🇱" },
  { name: "Portugal", code: "+351", iso: "pt", flag: "🇵🇹" },
  { name: "Qatar", code: "+974", iso: "qa", flag: "🇶🇦" },
  { name: "Romania", code: "+40", iso: "ro", flag: "🇷🇴" },
  { name: "Russia", code: "+7", iso: "ru", flag: "🇷🇺" },
  { name: "Rwanda", code: "+250", iso: "rw", flag: "🇷🇼" },
  { name: "Saint Kitts and Nevis", code: "+1869", iso: "kn", flag: "🇰🇳" },
  { name: "Saint Lucia", code: "+1758", iso: "lc", flag: "🇱🇨" },
  {
    name: "Saint Vincent and the Grenadines",
    code: "+1784",
    iso: "vc",
    flag: "🇻🇨",
  },
  { name: "Samoa", code: "+685", iso: "ws", flag: "🇼🇸" },
  { name: "San Marino", code: "+378", iso: "sm", flag: "🇸🇲" },
  { name: "São Tomé and Príncipe", code: "+239", iso: "st", flag: "🇸🇹" },
  { name: "Saudi Arabia", code: "+966", iso: "sa", flag: "🇸🇦" },
  { name: "Senegal", code: "+221", iso: "sn", flag: "🇸🇳" },
  { name: "Serbia", code: "+381", iso: "rs", flag: "🇷🇸" },
  { name: "Seychelles", code: "+248", iso: "sc", flag: "🇸🇨" },
  { name: "Sierra Leone", code: "+232", iso: "sl", flag: "🇸🇱" },
  { name: "Singapore", code: "+65", iso: "sg", flag: "🇸🇬" },
  { name: "Slovakia", code: "+421", iso: "sk", flag: "🇸🇰" },
  { name: "Slovenia", code: "+386", iso: "si", flag: "🇸🇮" },
  { name: "Solomon Islands", code: "+677", iso: "sb", flag: "🇸🇧" },
  { name: "Somalia", code: "+252", iso: "so", flag: "🇸🇴" },
  { name: "Somaliland", code: "+252", iso: "", flag: "🏴" },
  { name: "South Africa", code: "+27", iso: "za", flag: "🇿🇦" },
  { name: "South Korea", code: "+82", iso: "kr", flag: "🇰🇷" },
  { name: "South Sudan", code: "+211", iso: "ss", flag: "🇸🇸" },
  { name: "Spain", code: "+34", iso: "es", flag: "🇪🇸" },
  { name: "Sri Lanka", code: "+94", iso: "lk", flag: "🇱🇰" },
  { name: "Sudan", code: "+249", iso: "sd", flag: "🇸🇩" },
  { name: "Suriname", code: "+597", iso: "sr", flag: "🇸🇷" },
  { name: "Swaziland", code: "+268", iso: "sz", flag: "🇸🇿" },
  { name: "Sweden", code: "+46", iso: "se", flag: "🇸🇪" },
  { name: "Switzerland", code: "+41", iso: "ch", flag: "🇨🇭" },
  { name: "Syria", code: "+963", iso: "sy", flag: "🇸🇾" },
  { name: "Taiwan", code: "+886", iso: "tw", flag: "🇹🇼" },
  { name: "Tajikistan", code: "+992", iso: "tj", flag: "🇹🇯" },
  { name: "Tanzania", code: "+255", iso: "tz", flag: "🇹🇿" },
  { name: "Thailand", code: "+66", iso: "th", flag: "🇹🇭" },
  { name: "Togo", code: "+228", iso: "tg", flag: "🇹🇬" },
  { name: "Tonga", code: "+676", iso: "to", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", code: "+1868", iso: "tt", flag: "🇹🇹" },
  { name: "Tunisia", code: "+216", iso: "tn", flag: "🇹🇳" },
  { name: "Turkey", code: "+90", iso: "tr", flag: "🇹🇷" },
  { name: "Turkmenistan", code: "+993", iso: "tm", flag: "🇹🇲" },
  { name: "Tuvalu", code: "+688", iso: "tv", flag: "🇹🇻" },
  { name: "Uganda", code: "+256", iso: "ug", flag: "🇺🇬" },
  { name: "Ukraine", code: "+380", iso: "ua", flag: "🇺🇦" },
  { name: "United Arab Emirates", code: "+971", iso: "ae", flag: "🇦🇪" },
  { name: "United Kingdom", code: "+44", iso: "gb", flag: "🇬🇧" },
  { name: "United States", code: "+1", iso: "us", flag: "🇺🇸" },
  { name: "Uruguay", code: "+598", iso: "uy", flag: "🇺🇾" },
  { name: "Uzbekistan", code: "+998", iso: "uz", flag: "🇺🇿" },
  { name: "Vanuatu", code: "+678", iso: "vu", flag: "🇻🇺" },
  { name: "Vatican City", code: "+379", iso: "va", flag: "🇻🇦" },
  { name: "Venezuela", code: "+58", iso: "ve", flag: "🇻🇪" },
  { name: "Vietnam", code: "+84", iso: "vn", flag: "🇻🇳" },
  { name: "Yemen", code: "+967", iso: "ye", flag: "🇾🇪" },
  { name: "Zambia", code: "+260", iso: "zm", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "+263", iso: "zw", flag: "🇿🇼" },
] as const;
