export const products = [
  {
    slug: "lvl-board",
    name: "LVL Board",
    fullName: "Laminated Veneer Lumber Board",
    description: "High-strength engineered wood for structural applications",
    image: "/images/products/lvl-board.jpg",
    detailedDescription:
      "LVL (Laminated Veneer Lumber) is an engineered wood product that uses multiple layers of thin wood assembled with adhesives. It offers superior strength and stability compared to conventional lumber, making it ideal for structural applications in construction.",
    features: [
      "High load-bearing capacity",
      "Consistent quality and strength",
      "Dimensional stability",
      "Resistant to warping and shrinking",
      "Available in various sizes and grades",
    ],
    applications: [
      "Beams and headers",
      "Rafters and joists",
      "Scaffold planking",
      "Structural framing",
      "Floor and roof systems",
    ],
    specifications: [
      "Thickness: 18mm - 90mm",
      "Width: Up to 1220mm",
      "Length: Custom lengths available",
      "Density: 500-600 kg/m³",
    ],
  },
  {
    slug: "white-wood",
    name: "White Wood",
    fullName: "Premium White Wood Timber",
    description: "Premium quality softwood for construction and finishing",
    image: "/images/products/white-wood.jpg",
    detailedDescription:
      "White wood is premium quality softwood timber sourced from sustainable forests. Known for its light color and fine grain, it is ideal for both structural and decorative applications in construction and interior design.",
    features: [
      "Light natural color",
      "Fine, even grain",
      "Easy to work with",
      "Good finishing properties",
      "Sustainable sourcing",
    ],
    applications: [
      "Interior framing",
      "Furniture making",
      "Decorative trim and molding",
      "Ceiling and wall cladding",
      "General carpentry",
    ],
    specifications: [
      "Thickness: 12mm - 50mm",
      "Width: Various standard sizes",
      "Length: 2440mm - 3660mm",
      "Moisture content: 12-15%",
    ],
  },
  {
    slug: "scaffolding-board",
    name: "Scaffolding Board",
    fullName: "Scaffolding Board / Plank",
    description: "Durable boards for safe scaffolding systems",
    image: "/images/products/scaffolding-board.jpg",
    detailedDescription:
      "Our scaffolding boards are manufactured to meet strict safety standards for construction scaffolding. Made from strong, treated timber, they provide a safe working platform for construction workers at height.",
    features: [
      "High load capacity",
      "Treated for durability",
      "Weather resistant",
      "Compliant with safety standards",
      "Non-slip surface available",
    ],
    applications: [
      "Scaffolding platforms",
      "Working platforms",
      "Temporary walkways",
      "Construction access",
      "Formwork support",
    ],
    specifications: [
      "Thickness: 38mm standard",
      "Width: 225mm standard",
      "Length: 3.9m - 4.8m",
      "Load capacity: Up to 270kg",
    ],
  },
  {
    slug: "film-faced-plywood",
    name: "Film Faced Plywood",
    fullName: "Film Faced Shuttering Plywood",
    description: "Water-resistant plywood for concrete formwork",
    image: "/images/products/film-faced-plywood.jpg",
    detailedDescription:
      "Film faced plywood is specially designed for concrete formwork applications. With a durable film coating on both sides, it provides a smooth finish to concrete and can be reused multiple times, making it cost-effective for large construction projects.",
    features: [
      "Water and moisture resistant",
      "Smooth phenolic film surface",
      "High reusability (30+ pours)",
      "Excellent concrete finish",
      "Available in various grades",
    ],
    applications: [
      "Concrete formwork",
      "Shuttering",
      "Wall and slab forming",
      "Column formwork",
      "Bridge construction",
    ],
    specifications: [
      "Thickness: 12mm, 15mm, 18mm, 21mm",
      "Size: 1220 x 2440mm, 1250 x 2500mm",
      "Core: Poplar, Hardwood, Combi",
      "Film: Phenolic, Brown/Black",
    ],
  },
  {
    slug: "h20-beam",
    name: "H20 Beam",
    fullName: "H20 Timber Beam for Formwork",
    description: "Strong support beams for formwork systems",
    image: "/images/products/h20-beam.jpg",
    detailedDescription:
      "H20 beams are specialized formwork beams designed for high-performance concrete forming systems. With an I-beam profile, they offer excellent load-bearing capacity while remaining lightweight and easy to handle.",
    features: [
      "High load-bearing capacity",
      "Lightweight design",
      "Durable construction",
      "Compatible with standard accessories",
      "Long service life",
    ],
    applications: [
      "Slab formwork",
      "Table formwork systems",
      "Wall formwork support",
      "Beam and column formwork",
      "Bridge deck construction",
    ],
    specifications: [
      "Height: 200mm standard",
      "Length: 2.65m - 5.90m",
      "Flange width: 80mm",
      "Web thickness: 15mm",
    ],
  },
  {
    slug: "hardboard",
    name: "Hardboard",
    fullName: "High-Density Hardboard",
    description: "Dense fiberboard for interior applications",
    image: "/images/products/hardboard.webp",
    detailedDescription:
      "Hardboard is a high-density fiberboard product made from compressed wood fibers. It provides a smooth, durable surface ideal for interior finishing, furniture backing, and various construction applications.",
    features: [
      "High density and strength",
      "Smooth surface finish",
      "Easy to paint and laminate",
      "Cost-effective",
      "Available in various thicknesses",
    ],
    applications: [
      "Furniture backing",
      "Drawer bottoms",
      "Wall paneling",
      "Underlayment",
      "Craft and DIY projects",
    ],
    specifications: [
      "Thickness: 3mm, 4mm, 6mm",
      "Size: 1220 x 2440mm standard",
      "Density: 800-1000 kg/m³",
      "Surface: Smooth one side (S1S) or both sides (S2S)",
    ],
  },
  {
    slug: "commercial-plywood",
    name: "Commercial Plywood",
    fullName: "Commercial Grade Plywood",
    description: "Versatile plywood for various construction needs",
    image: "/images/products/commercial-plywood.jpg",
    detailedDescription:
      "Commercial plywood is a versatile engineered wood panel suitable for a wide range of construction and interior applications. Made from multiple layers of wood veneers, it offers good strength, stability, and value for money.",
    features: [
      "Good strength-to-weight ratio",
      "Versatile application",
      "Cost-effective solution",
      "Available in multiple grades",
      "Easy to work with",
    ],
    applications: [
      "Interior partitions",
      "Furniture construction",
      "Cabinetry",
      "General construction",
      "Packaging and crating",
    ],
    specifications: [
      "Thickness: 4mm - 25mm",
      "Size: 1220 x 2440mm, 1220 x 1830mm",
      "Core: Hardwood, Poplar",
      "Grade: BB/CC, C/D",
    ],
  },
];

export const siteSettings = {
  name: "Timber Souq",
  description: "Your one-stop shop for quality timber and wood products.",
  address: "123 Timber St, Woodsville, WS 12345",
  phone: "+1 (555) 123-4567",
  email: "info@timbersouq.com",
  social: {
    facebook: "https://facebook.com/timbersouq",
    instagram: "https://instagram.com/timbersouq",
    twitter: "https://twitter.com/timbersouq",
  },
  favicon: [{ url: "/favicon/timbersouq.svg", type: "image/svg+xml" }],
};
