export const products = [
  {
    slug: "lvl-board",
    name: "LVL Board",
    fullName: "Laminated Veneer Lumber Board",
    description: "High-strength engineered wood for structural applications",
    image: "/timbersouq/images/products/lvl-board.webp",
    detailedDescription:
      "LVL (Laminated Veneer Lumber) is an engineered wood product that uses multiple layers of thin wood assembled with adhesives. It offers superior strength and stability compared to conventional lumber, making it ideal for structural applications in construction.",
    features: [
      "High load-bearing capacity",
      "Consistent quality and strength",
      "Dimensional stability",
      "Resistant to warping and shrinking",
      "Available in various sizes and grades",
    ],
    applications: [
      "Beams and headers",
      "Rafters and joists",
      "Scaffold planking",
      "Structural framing",
      "Floor and roof systems",
    ],
    specifications: [
      "Origin: China(OSHA Standard)",
      "Width: 225mm",
      "Length: 1meter to 4meter",
      "Thickness: 38mm",
      "Stock Availability: In Stock",
    ],
  },
  {
    slug: "white-wood",
    name: "White Wood",
    fullName: "Premium White Wood Timber",
    description: "Premium quality softwood for construction and finishing",
    image: "/timbersouq/images/products/white-wood.jpg",
    detailedDescription:
      "White wood is premium quality softwood timber sourced from sustainable forests. Known for its light color and fine grain, it is ideal for both structural and decorative applications in construction and interior design.",
    features: [
      "Light natural color",
      "Fine, even grain",
      "Easy to work with",
      "Good finishing properties",
      "Sustainable sourcing",
    ],
    applications: [
      "Interior framing",
      "Furniture making",
      "Decorative trim and molding",
      "Ceiling and wall cladding",
      "General carpentry",
    ],
    specifications: [
      "Origin:	Austria, Germany, Romania",
      "Width: 2inch to 12inch",
      "Length: 10ft to 13ft",
      "Thickness: 1inch to 4inch",
      "Stock Availability: In Stock",
    ],
  },
  {
    slug: "scaffolding-board",
    name: "Scaffolding Board",
    fullName: "Scaffolding Board / Plank",
    description: "Durable boards for safe scaffolding systems",
    image: "/timbersouq/images/products/scaffolding-board.webp",
    detailedDescription:
      "Our scaffolding boards are manufactured to meet strict safety standards for construction scaffolding. Made from strong, treated timber, they provide a safe working platform for construction workers at height.",
    features: [
      "High load capacity",
      "Treated for durability",
      "Weather resistant",
      "Compliant with safety standards",
      "Non-slip surface available",
    ],
    applications: [
      "Scaffolding platforms",
      "Working platforms",
      "Temporary walkways",
      "Construction access",
      "Formwork support",
    ],
    specifications: [
      "Origin: Austria",
      "Width: 225mm",
      "Length: 1m to 4m",
      "Thickness: 38mm",
      "Stock Availability: In Stock",
    ],
  },
  {
    slug: "film-faced-plywood",
    name: "Film Faced Plywood",
    fullName: "Film Faced Shuttering Plywood",
    description: "Water-resistant plywood for concrete formwork",
    image: "/timbersouq/images/products/film-faced-plywood.jpg",
    detailedDescription:
      "Film faced plywood is specially designed for concrete formwork applications. With a durable film coating on both sides, it provides a smooth finish to concrete and can be reused multiple times, making it cost-effective for large construction projects.",
    features: [
      "Water and moisture resistant",
      "Smooth phenolic film surface",
      "High reusability (30+ pours)",
      "Excellent concrete finish",
      "Available in various grades",
    ],
    applications: [
      "Concrete formwork",
      "Shuttering",
      "Wall and slab forming",
      "Column formwork",
      "Bridge construction",
    ],
    specifications: [
      "Origin: Indonesia, China, Malaysia",
      "Width: 225mm",
      "Length: 1m to 4m",
      "Thickness: 38mm",
      "Stock Availability: In Stock",
    ],
  },
  {
    slug: "h20-beam",
    name: "H20 Beam",
    fullName: "H20 Timber Beam for Formwork",
    description: "Strong support beams for formwork systems",
    image: "/timbersouq/images/products/h20-beam.jpg",
    detailedDescription:
      "H20 beams are specialized formwork beams designed for high-performance concrete forming systems. With an I-beam profile, they offer excellent load-bearing capacity while remaining lightweight and easy to handle.",
    features: [
      "High load-bearing capacity",
      "Lightweight design",
      "Durable construction",
      "Compatible with standard accessories",
      "Long service life",
    ],
    applications: [
      "Slab formwork",
      "Table formwork systems",
      "Wall formwork support",
      "Beam and column formwork",
      "Bridge deck construction",
    ],
    specifications: [
      "Origin: Europe",
      "Width: 200mm",
      "Cord: 40mm(Lower & Upper Element)",
      "Core Width: 80mm",
      "Length: 1.9m to 5.9m",
      "Packaging: 100pcs/bundle | 105pcs/bundle",
      "Stock Availability: In Stock",
    ],
  },
  // {
  //   slug: "hardboard",
  //   name: "Hardboard",
  //   fullName: "High-Density Hardboard",
  //   description: "Dense fiberboard for interior applications",
  //   image: "/timbersouq/images/products/hardboard.webp",
  //   detailedDescription:
  //     "Hardboard is a high-density fiberboard product made from compressed wood fibers. It provides a smooth, durable surface ideal for interior finishing, furniture backing, and various construction applications.",
  //   features: [
  //     "High density and strength",
  //     "Smooth surface finish",
  //     "Easy to paint and laminate",
  //     "Cost-effective",
  //     "Available in various thicknesses",
  //   ],
  //   applications: [
  //     "Furniture backing",
  //     "Drawer bottoms",
  //     "Wall paneling",
  //     "Underlayment",
  //     "Craft and DIY projects",
  //   ],
  //   specifications: [
  //     "Origin: Thailand, India, China",
  //     "Width: 1220mm",
  //     "Length: 2440mm",
  //     "Thickness: 2.4mm to 13mm",
  //     "Stock Availability: In Stock",
  //   ],
  // },
  {
    slug: "commercial-plywood",
    name: "Commercial Plywood",
    fullName: "Commercial Grade Plywood",
    description: "Versatile plywood for various construction needs",
    image: "/timbersouq/images/products/commercial-plywood.jpg",
    detailedDescription:
      "Commercial plywood is a versatile engineered wood panel suitable for a wide range of construction and interior applications. Made from multiple layers of wood veneers, it offers good strength, stability, and value for money.",
    features: [
      "Good strength-to-weight ratio",
      "Versatile application",
      "Cost-effective solution",
      "Available in multiple grades",
      "Easy to work with",
    ],
    applications: [
      "Interior partitions",
      "Furniture construction",
      "Cabinetry",
      "General construction",
      "Packaging and crating",
    ],
    specifications: [
      "Origin: China, Malaysia",
      "Width: 1220mm",
      "Length: 2440mm",
      "Thickness: 2.5mm to 24mm",
      "Stock Availability: In Stock",
    ],
  },
  {
    slug: "galvanized-iron-sheets",
    name: "Galvanized Iron (GI) sheets",
    fullName: "Galvanized Iron (GI) Sheets",
    description: "Corrosion-resistant galvanized iron sheets for construction",
    image: "/timbersouq/images/products/galvanized-iron-sheets.webp",
    detailedDescription:
      "Galvanized Iron (GI) Sheets are steel sheets coated with a layer of zinc to prevent rust and corrosion. They are widely used in roofing, cladding, and general construction due to their durability and long service life.",
    features: [
      "Zinc-coated for corrosion resistance",
      "High tensile strength",
      "Lightweight and easy to handle",
      "Long service life",
      "Available in various gauges",
    ],
    applications: [
      "Roofing and cladding",
      "Ductwork and ventilation",
      "Wall and ceiling panels",
      "Industrial enclosures",
      "General fabrication",
    ],
    specifications: [
      "Origin: China, India",
      "Width: 1000mm / 1220mm",
      "Length: 2440mm",
      "Thickness: 0.3mm to 3mm",
      "Stock Availability: In Stock",
    ],
  },
  {
    slug: "iron-rebar",
    name: "Iron Rebar",
    fullName: "Deformed Steel Reinforcement Bar",
    description: "High-strength steel bars for concrete reinforcement",
    image: "/timbersouq/images/products/iron-rebar.webp",
    detailedDescription:
      "Iron Rebar (reinforcing bar) is a deformed steel bar used to reinforce concrete structures. The ribbed surface provides superior bonding with concrete, enhancing tensile strength and structural integrity in buildings, bridges, and infrastructure.",
    features: [
      "High yield strength",
      "Deformed surface for superior concrete bonding",
      "Excellent ductility",
      "Weldable grade available",
      "Compliant with international standards",
    ],
    applications: [
      "Reinforced concrete slabs",
      "Columns and beams",
      "Foundation and footings",
      "Retaining walls",
      "Bridge and infrastructure construction",
    ],
    specifications: [
      "Origin: UAE, Turkey, China",
      "Diameter: 8mm to 32mm",
      "Length: 6m / 12m",
      "Grade: Grade 60 / BS4449",
      "Stock Availability: In Stock",
    ],
  },
  {
    slug: "red-wood",
    name: "Red Wood",
    fullName: "Premium Redwood Timber",
    description:
      "Durable and naturally beautiful redwood for construction and joinery",
    image: "/timbersouq/images/products/red-wood.jpg",
    detailedDescription:
      "Redwood timber is prized for its rich reddish-brown color, natural durability, and resistance to decay. Sourced from sustainable forests, it is an excellent choice for both structural and decorative applications, offering a premium finish that stands the test of time.",
    features: [
      "Natural decay and insect resistance",
      "Rich, warm reddish-brown tone",
      "Stable and low shrinkage",
      "Easy to machine and finish",
      "Sustainably sourced",
    ],
    applications: [
      "Outdoor decking and cladding",
      "Doors and window frames",
      "Furniture and joinery",
      "Interior paneling",
      "Structural framing",
    ],
    specifications: [
      "Origin: USA, Scandinavia",
      "Width: 2inch to 12inch",
      "Length: 8ft to 16ft",
      "Thickness: 1inch to 4inch",
      "Stock Availability: In Stock",
    ],
  },
];

export const siteSettings = {
  name: "Timber Souq",
  description: "Your one-stop shop for quality timber and wood products.",
  address:
    "Suite 503, Platinum Business Centre, Baghdad Street, 7A Street, Al Nahda 2, Dubai, UAE",
  phone: "+971 4 251 2418",
  email: "info@timbersouq.com",
  social: {
    facebook: "https://facebook.com/timbersouq",
    instagram: "https://instagram.com/timbersouq",
    twitter: "https://twitter.com/timbersouq",
  },
  favicon: [{ url: "/favicon/timbersouq.svg", type: "image/svg+xml" }],
};
